import Footer from '@/components/Footer'
import Header from '@/components/Header'
import '@/styles/globals.css'
import Head from 'next/head'
import { store } from "@/store/store";
import { Provider } from 'react-redux'


export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Shop store</title>
        <meta name='description' content='Generated By next app'></meta>
        <meta name='viewport' content='width=device-width, initial-scale=1'></meta>
        <link rel='icon' href='/logo.svg' />
      </Head>
      <Provider store={store}>
        <Header />
        <Component {...pageProps} />
        <Footer />
      </Provider>
    </>
  )
}
